### PR TITLE
Add gRPC SLOs

### PR DESCRIPTION
**Pull request by kakkoyun**
Attempt to add gRPC SLOs #15

### CODE REVIEW

**Comment by metalmatze** [comment]
Once we make use of this in the kube-thanos project, I'm happy to merge this as well. Or do you think we should merge already?

**Comment by kakkoyun** [comment]
Let's merge it after we experience the usage in kube-thanos.

**Comment by kakkoyun** [comment]
@metalmatze I'm closing this one, it needs a lot of reconsideration after recent changes,

**Comment by metalmatze** [comment]
Thanks for working on it anyway!
We should review the recent additions to whether we can make use of those for gRPC too (which they should be)

**Pull request closed without merging**
